[env:esp32-c3-devkitm-1]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
; upload to app0
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.offset_address = 0x10000
; board_upload.offset_address = 0x650000 
; Board configuration
board_build.flash_mode = dio
board_build.flash_size = 16MB
board_build.partitions = partitions.csv

; Libraries
lib_deps =
    zinggjm/GxEPD2@^1.5.9
    core=symlink://core

; Build flags
build_flags =
    -Isrc
    -DBASEDIR=\"/sd/\"
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDEBUG_IO=1
    -DXML_GE=0
    -DXML_CONTEXT_BYTES=1024
    -std=c++26
    -DMINIZ_NO_MALLOC -DMINIZ_NO_DEFLATE_APIS -DMINIZ_NO_STDIO -DMINIZ_NO_TIME -DMINIZ_NO_ARCHIVE_APIS -DMINIZ_NO_ZLIB_APIS

extra_scripts = pre:pre_compile_flags.py
